import { Column, Entity, Index } from "typeorm";
import { BaseEntity } from "../common/base.entity";
import type { SourceLink, SubmissionStatus } from "./report-submission.constants";

/** A report a user asked RUWĀD to publish. Only an approved submission produces a row in `reports`, so a pending or
 * rejected one can never surface through any existing public report query. Everything here is raw data — display
 * formatting happens on the client. */
@Entity("report_submissions")
@Index("IDX_report_submissions_user_idem", ["userId", "idempotencyKey"], { unique: true })
export class ReportSubmission extends BaseEntity {
  @Index() @Column({ type: "uuid" }) userId!: string;

  @Column() title!: string;
  @Column() reportType!: string;
  @Column() sector!: string;
  @Column() geography!: string;
  @Column({ type: "date", nullable: true }) publicationDate?: string | null;
  @Column({ type: "text" }) description!: string;
  @Column({ type: "text" }) executiveSummary!: string;

  @Column() authorName!: string;
  @Column() organizationName!: string;
  @Column() authorEmail!: string;
  @Column({ type: "varchar", nullable: true }) website?: string | null;
  @Column({ type: "varchar", nullable: true }) linkedin?: string | null;

  @Column({ type: "varchar", nullable: true }) reportUrl?: string | null;
  @Column({ type: "uuid", nullable: true }) fileId?: string | null;
  @Column({ type: "jsonb", default: [] }) sources!: SourceLink[];
  @Column({ default: false }) declarationAccepted!: boolean;

  @Index() @Column({ type: "varchar", default: "PENDING_REVIEW" }) status!: SubmissionStatus;
  /** Generated by the form when it opens; repeating a submit with the same key returns the first request. */
  @Column({ type: "varchar" }) idempotencyKey!: string;
  @Column({ type: "timestamptz" }) submittedAt!: Date;

  // Moderation history
  @Column({ type: "timestamptz", nullable: true }) reviewedAt?: Date | null;
  @Column({ type: "varchar", nullable: true }) reviewAction?: "ACCEPT" | "REJECT" | null;
  /** Null when the decision came from the emailed review link (nobody was signed in). */
  @Column({ type: "uuid", nullable: true }) reviewedByUserId?: string | null;
  @Column({ type: "varchar", nullable: true }) reviewedVia?: "EMAIL_TOKEN" | null;
  @Column({ type: "text", nullable: true }) rejectionReason?: string | null;
  @Column({ type: "timestamptz", nullable: true }) rejectedAt?: Date | null;
  @Column({ type: "timestamptz", nullable: true }) publishedAt?: Date | null;
  @Column({ type: "uuid", nullable: true }) publishedReportId?: string | null;

  // Review-email delivery, so a failed send is visible and can be retried
  @Column({ type: "timestamptz", nullable: true }) reviewEmailSentAt?: Date | null;
  @Column({ type: "int", default: 0 }) reviewEmailAttempts!: number;
}
