import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1788897746772 implements MigrationInterface {
    name = 'InitialSchema1788897746772'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."watchlist_items_kind_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL', 'REPORT')`);
        await queryRunner.query(`CREATE TABLE "watchlist_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "kind" "public"."watchlist_items_kind_enum" NOT NULL, "entityId" uuid NOT NULL, CONSTRAINT "UQ_1573ed4e27c9acf2299a745889e" UNIQUE ("userId", "kind", "entityId"), CONSTRAINT "PK_0a02323c5cc02e094871f24062b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1d44d0b2e52ecad244c712dfaf" ON "watchlist_items" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('USER', 'FOUNDER', 'INVESTOR', 'ORGANIZATION_ADMIN', 'RUWAD_ADMIN', 'SUPER_ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "jobTitle" character varying, "organization" character varying, "country" character varying, "city" character varying, "bio" text, "linkedin" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'USER', "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "user_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "emailNotifications" boolean NOT NULL DEFAULT true, "introRequestAlerts" boolean NOT NULL DEFAULT true, "savedSearchAlerts" boolean NOT NULL DEFAULT true, "weeklyDigest" boolean NOT NULL DEFAULT false, "profileVisibleToGuests" boolean NOT NULL DEFAULT true, "showContactInfo" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_986a2b6d3c05eb4091bb8066f7" UNIQUE ("userId"), CONSTRAINT "PK_00f004f5922a0744d174530d639" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_986a2b6d3c05eb4091bb8066f7" ON "user_settings" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."submissions_kind_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TYPE "public"."submissions_status_enum" AS ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "kind" "public"."submissions_kind_enum" NOT NULL, "entityId" uuid, "payload" jsonb NOT NULL, "status" "public"."submissions_status_enum" NOT NULL DEFAULT 'SUBMITTED', "reviewerNote" text, CONSTRAINT "PK_10b3be95b8b2fb1e482e07d706b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eae888413ab8fc63cc48759d46" ON "submissions" ("userId") `);
        await queryRunner.query(`CREATE TABLE "startups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "category" character varying NOT NULL, "subsector" character varying NOT NULL, "tagline" character varying NOT NULL, "country" character varying NOT NULL, "city" character varying NOT NULL, "hq" character varying NOT NULL, "founded" integer NOT NULL, "stage" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'Active', "businessModel" character varying NOT NULL, "employees" integer NOT NULL, "fundingTotal" numeric(12,2) NOT NULL, "valuation" numeric(12,2) NOT NULL, "fundraising" boolean NOT NULL DEFAULT false, "targetRaise" character varying, "desc" text NOT NULL, "problem" text NOT NULL, "solution" text NOT NULL, "advantage" text NOT NULL, "sfda" character varying NOT NULL, "fda" character varying NOT NULL, "ce" character varying NOT NULL, "clinicalStatus" character varying NOT NULL, "patentStatus" character varying NOT NULL, "marketTam" character varying NOT NULL, "marketSam" character varying NOT NULL, "marketSom" character varying NOT NULL, "marketCompetitors" text array NOT NULL DEFAULT '{}', "legalName" character varying NOT NULL, "formerName" character varying NOT NULL DEFAULT '—', "website" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "linkedin" character varying NOT NULL, "registrationNumber" character varying NOT NULL, "verified" character varying NOT NULL DEFAULT 'unclaimed', "scoreGrowth" integer NOT NULL, "scoreFinancial" integer NOT NULL, "scoreMarket" integer NOT NULL, "scoreTeam" integer NOT NULL, "scoreRegulatory" integer NOT NULL, "scoreTech" integer NOT NULL, "score" integer NOT NULL, "provenanceConfidence" character varying NOT NULL DEFAULT 'Medium', "provenanceLastUpdated" date NOT NULL, "provenanceSources" text array NOT NULL DEFAULT '{}', CONSTRAINT "PK_d3f4c6833156641c6dfdbee31b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5bfbfd5dae6fa8df946b799713" ON "startups" ("slug") `);
        await queryRunner.query(`CREATE TABLE "funding_rounds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "startupId" uuid NOT NULL, "round" character varying NOT NULL, "date" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "lead" character varying NOT NULL, CONSTRAINT "PK_97ceda929557b9a726c83108962" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_192a27decba357431d76cfdd34" ON "funding_rounds" ("startupId") `);
        await queryRunner.query(`CREATE TABLE "saved_searches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "entityType" character varying NOT NULL, "label" character varying NOT NULL, "search" character varying NOT NULL DEFAULT '', "filters" jsonb NOT NULL DEFAULT '{}', "resultCountAtSave" integer NOT NULL DEFAULT '0', "lastRunAt" TIMESTAMP WITH TIME ZONE, "alertEnabled" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d9a53c71ccc5cf66dcdc5b33dfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_507a6228007bed5e89b3a29157" ON "saved_searches" ("userId") `);
        await queryRunner.query(`CREATE TABLE "research_institutions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "city" character varying NOT NULL, "country" character varying NOT NULL, "founded" integer NOT NULL, "website" character varying NOT NULL, "numResearchers" integer NOT NULL, "numCenters" integer NOT NULL, "numLabs" integer NOT NULL, "about" text NOT NULL, "collaborationStatus" character varying NOT NULL DEFAULT 'Selective', "technologyReadinessLevel" integer NOT NULL, "patentsCount" integer NOT NULL, "provenanceConfidence" character varying NOT NULL DEFAULT 'Medium', "provenanceLastUpdated" date NOT NULL, "provenanceSources" text array NOT NULL DEFAULT '{}', CONSTRAINT "PK_54bc946b9ce951eb74c7d43d0af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_974e6beb5407b012dfa33485df" ON "research_institutions" ("slug") `);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "slug" character varying NOT NULL, "title" character varying NOT NULL, "category" character varying NOT NULL, "reportType" character varying NOT NULL, "publicationDate" date NOT NULL, "description" text NOT NULL, "geography" character varying NOT NULL, "sector" character varying NOT NULL, "authors" text array NOT NULL DEFAULT '{}', "readingTime" character varying NOT NULL, "pages" integer NOT NULL, "badges" text array NOT NULL DEFAULT '{}', "executiveSummary" text NOT NULL, "keyFindings" text array NOT NULL DEFAULT '{}', "marketStats" jsonb NOT NULL DEFAULT '[]', "sections" jsonb NOT NULL DEFAULT '[]', "sources" text array NOT NULL DEFAULT '{}', "relatedStartupIds" uuid array NOT NULL DEFAULT '{}', "relatedInvestorIds" uuid array NOT NULL DEFAULT '{}', "relatedReportIds" uuid array NOT NULL DEFAULT '{}', "publishedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5647565acf4e78f87be0b68471" ON "reports" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."entity_memberships_kind_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TYPE "public"."entity_memberships_role_enum" AS ENUM('OWNER', 'ADMIN', 'EDITOR', 'VIEWER')`);
        await queryRunner.query(`CREATE TYPE "public"."entity_memberships_listingstatus_enum" AS ENUM('PUBLISHED', 'DRAFT', 'UNDER_REVIEW', 'CHANGES_REQUESTED')`);
        await queryRunner.query(`CREATE TYPE "public"."entity_memberships_listingvisibility_enum" AS ENUM('PUBLIC', 'UNLISTED')`);
        await queryRunner.query(`CREATE TABLE "entity_memberships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "kind" "public"."entity_memberships_kind_enum" NOT NULL, "entityId" uuid NOT NULL, "role" "public"."entity_memberships_role_enum" NOT NULL DEFAULT 'OWNER', "listingStatus" "public"."entity_memberships_listingstatus_enum" NOT NULL DEFAULT 'PUBLISHED', "listingVisibility" "public"."entity_memberships_listingvisibility_enum" NOT NULL DEFAULT 'PUBLIC', "views" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_6fafb3307c671133a9e5cbed8ee" UNIQUE ("userId", "kind", "entityId"), CONSTRAINT "PK_c3f868e151fd275dd7c089688f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_507e3ca4058d152b49a3508293" ON "entity_memberships" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9be761014086289206a9cb97b" ON "entity_memberships" ("entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."news_related_entities_entitytype_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TABLE "news_related_entities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "newsId" uuid NOT NULL, "entityType" "public"."news_related_entities_entitytype_enum" NOT NULL, "entityId" uuid NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_cf4717962c543eb506f5d3a8903" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2d26639fa111909292d23fa2ca" ON "news_related_entities" ("newsId") `);
        await queryRunner.query(`CREATE TABLE "news_articles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying NOT NULL, "source" character varying NOT NULL, "publishedDate" date NOT NULL, "category" character varying NOT NULL, "sector" character varying NOT NULL, "geography" character varying NOT NULL, "summary" text NOT NULL, "sourceUrl" character varying NOT NULL, CONSTRAINT "PK_ca1b67b1b6b2c382317bbd769dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "multinationals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "category" character varying NOT NULL, "subsector" character varying NOT NULL, "tagline" character varying NOT NULL, "country" character varying NOT NULL, "city" character varying NOT NULL, "hq" character varying NOT NULL, "founded" integer NOT NULL, "status" character varying NOT NULL DEFAULT 'Active', "businessModel" character varying NOT NULL, "employees" integer NOT NULL, "companySize" character varying NOT NULL, "desc" text NOT NULL, "problem" text NOT NULL, "solution" text NOT NULL, "advantage" text NOT NULL, "sfda" character varying NOT NULL, "fda" character varying NOT NULL, "ce" character varying NOT NULL, "clinicalStatus" character varying NOT NULL, "patentStatus" character varying NOT NULL, "marketTam" character varying NOT NULL, "marketSam" character varying NOT NULL, "marketSom" character varying NOT NULL, "marketCompetitors" text array NOT NULL DEFAULT '{}', "saudiOffice" boolean NOT NULL DEFAULT true, "regionalHeadquarters" boolean NOT NULL DEFAULT false, "manufacturing" boolean NOT NULL DEFAULT false, "distribution" boolean NOT NULL DEFAULT true, "clinicalOperations" boolean NOT NULL DEFAULT false, "trainingCenters" boolean NOT NULL DEFAULT false, "researchOperations" boolean NOT NULL DEFAULT false, "countriesActiveIn" text array NOT NULL DEFAULT '{}', "regionalEmployees" character varying NOT NULL, "rdFocus" character varying NOT NULL, "rdCenters" integer NOT NULL, "openInnovation" boolean NOT NULL DEFAULT true, "startupCollaboration" boolean NOT NULL DEFAULT true, "partnershipInterest" boolean NOT NULL DEFAULT true, "techScouting" boolean NOT NULL DEFAULT true, "legalName" character varying NOT NULL, "website" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "linkedin" character varying NOT NULL, "provenanceConfidence" character varying NOT NULL DEFAULT 'High', "provenanceLastUpdated" date NOT NULL, "provenanceSources" text array NOT NULL DEFAULT '{}', CONSTRAINT "PK_879713d84e49b476f11cb25d578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0e00e9a624d970a3f6cca7fc6c" ON "multinationals" ("slug") `);
        await queryRunner.query(`CREATE TABLE "investors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "short" character varying NOT NULL, "type" character varying NOT NULL, "city" character varying NOT NULL, "founded" integer NOT NULL, "desc" text NOT NULL, "thesis" text NOT NULL, "stageFocus" text array NOT NULL DEFAULT '{}', "ticket" character varying NOT NULL, "aum" character varying NOT NULL, "available" character varying NOT NULL, "investments" integer NOT NULL, "exits" integer NOT NULL, "hcDeals" integer NOT NULL, "provenanceConfidence" character varying NOT NULL DEFAULT 'Medium', "provenanceLastUpdated" date NOT NULL, "provenanceSources" text array NOT NULL DEFAULT '{}', CONSTRAINT "PK_7ab129212e4ce89e68d6a27ea4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a46dd5bc418d04888291966830" ON "investors" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."investments_targetentitytype_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TABLE "investments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "investorId" uuid NOT NULL, "targetEntityType" "public"."investments_targetentitytype_enum" NOT NULL, "targetEntityId" uuid NOT NULL, "round" character varying, "year" integer, CONSTRAINT "PK_a1263853f1a4fb8b849c1c9aff4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93332d5e49cd494527409e0be3" ON "investments" ("investorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_405047ca6c73cd6773171e03c5" ON "investments" ("targetEntityId") `);
        await queryRunner.query(`CREATE TYPE "public"."introductions_status_enum" AS ENUM('PENDING', 'IN_REVIEW', 'ACCEPTED', 'DECLINED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "introductions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "status" "public"."introductions_status_enum" NOT NULL DEFAULT 'PENDING', "investor" character varying, "startup" character varying, "reasonType" character varying, "reason" text, "message" text, "statusHistory" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_811d59fa8b5c5255e94438b348e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cab50efb91b377873b0a3a4ca1" ON "introductions" ("userId") `);
        await queryRunner.query(`CREATE TABLE "hubs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "city" character varying NOT NULL, "country" character varying NOT NULL, "founded" integer NOT NULL, "website" character varying NOT NULL, "operatingRegion" character varying NOT NULL, "ownershipType" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'Open', "deadline" character varying NOT NULL, "desc" text NOT NULL, "about" text NOT NULL, "stagesSupported" text array NOT NULL DEFAULT '{}', "geographicCoverage" text array NOT NULL DEFAULT '{}', "support" text array NOT NULL DEFAULT '{}', "fundingAvailable" character varying NOT NULL, "fundingType" character varying NOT NULL, "provenanceConfidence" character varying NOT NULL DEFAULT 'Medium', "provenanceLastUpdated" date NOT NULL, "provenanceSources" text array NOT NULL DEFAULT '{}', CONSTRAINT "PK_44b53d1f2b4568b26ce4710b843" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2fdd263d5ee41b0eb11bbcab8f" ON "hubs" ("slug") `);
        await queryRunner.query(`CREATE TABLE "hub_programs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "hubId" uuid NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "status" character varying NOT NULL, "duration" character varying NOT NULL, "location" character varying NOT NULL, "format" character varying NOT NULL, "deadline" character varying NOT NULL, "cohortSize" character varying NOT NULL, CONSTRAINT "PK_5de9332e43bab0b659063fc5153" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff76482d046934747d2d407f8f" ON "hub_programs" ("hubId") `);
        await queryRunner.query(`CREATE TABLE "hub_portfolio_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "hubId" uuid NOT NULL, "startupId" uuid, "companyName" character varying NOT NULL, "sector" character varying NOT NULL, "stage" character varying NOT NULL, "programName" character varying NOT NULL, "year" integer NOT NULL, CONSTRAINT "PK_838db4d8e05b5535c942ffd1d9b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de75293e6c22ee1faad93ae5a5" ON "hub_portfolio_items" ("hubId") `);
        await queryRunner.query(`CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "date" date NOT NULL, "location" character varying NOT NULL, "country" character varying NOT NULL, "type" character varying NOT NULL, "sector" character varying NOT NULL, "organizer" character varying NOT NULL, "description" text NOT NULL, "registrationStatus" character varying NOT NULL DEFAULT 'Open', "url" character varying NOT NULL, CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."team_members_entitytype_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TABLE "team_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "entityType" "public"."team_members_entitytype_enum" NOT NULL, "entityId" uuid NOT NULL, "name" character varying NOT NULL, "title" character varying NOT NULL, "isFounder" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_ca3eae89dcf20c9fd95bf7460aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b354b524b2d78c8cce9452fd89" ON "team_members" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_480e705ef376209122900d271b" ON "team_members" ("entityId") `);
        await queryRunner.query(`CREATE TABLE "sectors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, CONSTRAINT "PK_923fdda0dc12f59add7b3a1782f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1a10b192342e5165948f4dccef" ON "sectors" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."products_entitytype_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "entityType" "public"."products_entitytype_enum" NOT NULL, "entityId" uuid NOT NULL, "name" character varying NOT NULL, "category" character varying NOT NULL, "description" text NOT NULL, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_baa632dcb49481e41e59694594" ON "products" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0298c081af49e5546fa38e608" ON "products" ("entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."partnerships_entitytype_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TABLE "partnerships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "entityType" "public"."partnerships_entitytype_enum" NOT NULL, "entityId" uuid NOT NULL, "type" character varying NOT NULL, "partnerName" character varying NOT NULL, "description" text NOT NULL, CONSTRAINT "PK_55de3c169ff0d5d88e9a7cb0cd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7e17896b5ba73a13c4eb79103" ON "partnerships" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_432c7647877f5eb8716b879312" ON "partnerships" ("entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."entity_sectors_entitytype_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TABLE "entity_sectors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "entityType" "public"."entity_sectors_entitytype_enum" NOT NULL, "entityId" uuid NOT NULL, "sectorId" uuid NOT NULL, CONSTRAINT "PK_371c2732f3b3eddd74a404dd27c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c5c33023c74f2f7b412ef554d2" ON "entity_sectors" ("entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7fc937dac88ba8f02e49310e9" ON "entity_sectors" ("sectorId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c014b990406e6f4ceffabfa243" ON "entity_sectors" ("entityType", "entityId", "sectorId") `);
        await queryRunner.query(`CREATE TYPE "public"."entity_documents_entitytype_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TABLE "entity_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "entityType" "public"."entity_documents_entitytype_enum" NOT NULL, "entityId" uuid NOT NULL, "name" character varying NOT NULL, "onFile" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_bf05b4e77af883794a7afe30c40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1dee68e8560c2d8b27c0ef0dcc" ON "entity_documents" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d844640a8fbfa60d159ebe22e" ON "entity_documents" ("entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."contacts_entitytype_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "entityType" "public"."contacts_entitytype_enum" NOT NULL, "entityId" uuid NOT NULL, "mainContact" character varying, "email" character varying, "phone" character varying, "website" character varying, "linkedin" character varying, "extra" jsonb, CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_14afb0e1846bd945a7c430f940" ON "contacts" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."data_room_access_requests_kind_enum" AS ENUM('STARTUP', 'INVESTOR', 'HUB', 'RESEARCH', 'MULTINATIONAL')`);
        await queryRunner.query(`CREATE TYPE "public"."data_room_access_requests_status_enum" AS ENUM('LOCKED', 'REQUESTED', 'NDA_REQUIRED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "data_room_access_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "kind" "public"."data_room_access_requests_kind_enum" NOT NULL, "entityId" uuid NOT NULL, "status" "public"."data_room_access_requests_status_enum" NOT NULL DEFAULT 'REQUESTED', "ndaSignedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_436d07a20c8954352b34a712924" UNIQUE ("userId", "kind", "entityId"), CONSTRAINT "PK_560efcb860cd09a0b05909f4bf7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_828838235aa45468c0ff72be8d" ON "data_room_access_requests" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b015e7de7e3945762f0918060" ON "data_room_access_requests" ("entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."activity_logs_type_enum" AS ENUM('watchlist_add', 'watchlist_remove', 'search_saved', 'intro_submitted', 'listing_edited', 'profile_updated')`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "type" "public"."activity_logs_type_enum" NOT NULL, "text" character varying NOT NULL, "route" character varying, CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_597e6df96098895bf19d4b5ea4" ON "activity_logs" ("userId") `);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD CONSTRAINT "FK_986a2b6d3c05eb4091bb8066f78" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_settings" DROP CONSTRAINT "FK_986a2b6d3c05eb4091bb8066f78"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_597e6df96098895bf19d4b5ea4"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP TYPE "public"."activity_logs_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b015e7de7e3945762f0918060"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_828838235aa45468c0ff72be8d"`);
        await queryRunner.query(`DROP TABLE "data_room_access_requests"`);
        await queryRunner.query(`DROP TYPE "public"."data_room_access_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."data_room_access_requests_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14afb0e1846bd945a7c430f940"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP TYPE "public"."contacts_entitytype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d844640a8fbfa60d159ebe22e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1dee68e8560c2d8b27c0ef0dcc"`);
        await queryRunner.query(`DROP TABLE "entity_documents"`);
        await queryRunner.query(`DROP TYPE "public"."entity_documents_entitytype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c014b990406e6f4ceffabfa243"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7fc937dac88ba8f02e49310e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5c33023c74f2f7b412ef554d2"`);
        await queryRunner.query(`DROP TABLE "entity_sectors"`);
        await queryRunner.query(`DROP TYPE "public"."entity_sectors_entitytype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_432c7647877f5eb8716b879312"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7e17896b5ba73a13c4eb79103"`);
        await queryRunner.query(`DROP TABLE "partnerships"`);
        await queryRunner.query(`DROP TYPE "public"."partnerships_entitytype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0298c081af49e5546fa38e608"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_baa632dcb49481e41e59694594"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_entitytype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a10b192342e5165948f4dccef"`);
        await queryRunner.query(`DROP TABLE "sectors"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_480e705ef376209122900d271b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b354b524b2d78c8cce9452fd89"`);
        await queryRunner.query(`DROP TABLE "team_members"`);
        await queryRunner.query(`DROP TYPE "public"."team_members_entitytype_enum"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de75293e6c22ee1faad93ae5a5"`);
        await queryRunner.query(`DROP TABLE "hub_portfolio_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff76482d046934747d2d407f8f"`);
        await queryRunner.query(`DROP TABLE "hub_programs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2fdd263d5ee41b0eb11bbcab8f"`);
        await queryRunner.query(`DROP TABLE "hubs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cab50efb91b377873b0a3a4ca1"`);
        await queryRunner.query(`DROP TABLE "introductions"`);
        await queryRunner.query(`DROP TYPE "public"."introductions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_405047ca6c73cd6773171e03c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93332d5e49cd494527409e0be3"`);
        await queryRunner.query(`DROP TABLE "investments"`);
        await queryRunner.query(`DROP TYPE "public"."investments_targetentitytype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a46dd5bc418d04888291966830"`);
        await queryRunner.query(`DROP TABLE "investors"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e00e9a624d970a3f6cca7fc6c"`);
        await queryRunner.query(`DROP TABLE "multinationals"`);
        await queryRunner.query(`DROP TABLE "news_articles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d26639fa111909292d23fa2ca"`);
        await queryRunner.query(`DROP TABLE "news_related_entities"`);
        await queryRunner.query(`DROP TYPE "public"."news_related_entities_entitytype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9be761014086289206a9cb97b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_507e3ca4058d152b49a3508293"`);
        await queryRunner.query(`DROP TABLE "entity_memberships"`);
        await queryRunner.query(`DROP TYPE "public"."entity_memberships_listingvisibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."entity_memberships_listingstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."entity_memberships_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."entity_memberships_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5647565acf4e78f87be0b68471"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_974e6beb5407b012dfa33485df"`);
        await queryRunner.query(`DROP TABLE "research_institutions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_507a6228007bed5e89b3a29157"`);
        await queryRunner.query(`DROP TABLE "saved_searches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_192a27decba357431d76cfdd34"`);
        await queryRunner.query(`DROP TABLE "funding_rounds"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bfbfd5dae6fa8df946b799713"`);
        await queryRunner.query(`DROP TABLE "startups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eae888413ab8fc63cc48759d46"`);
        await queryRunner.query(`DROP TABLE "submissions"`);
        await queryRunner.query(`DROP TYPE "public"."submissions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."submissions_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_986a2b6d3c05eb4091bb8066f7"`);
        await queryRunner.query(`DROP TABLE "user_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d44d0b2e52ecad244c712dfaf"`);
        await queryRunner.query(`DROP TABLE "watchlist_items"`);
        await queryRunner.query(`DROP TYPE "public"."watchlist_items_kind_enum"`);
    }

}
